### ISSUE TITLE
Date'in saat, dakika, saniye gibi parametrelerinin set edilebilmesi

### ISSUE THREAD

**Issue by uozanyildiz** [kentkartlab/kk-date#12]
date'in saat, dakika, saniye gibi parametrelerinin set edilebilmesi gerekli
örn: new KkDate(start).set('minutes', 0).set('seconds', 0);

**Comment by orhanayd** [comment]
@uozanyildiz  'second, minute, hour, year' s takısı ile mi olmalı ? öneriniz nedir ?
cc: @phoique

**Comment by phoique** [comment]
> @uozanyildiz 'second, minute, hour, year' s takısı ile mi olmalı ? öneriniz nedir ? cc: @phoique

'second, minute...' şeklinde daha uygun olacağını düşünüyorum.

**Comment by orhanayd** [comment]
Merged
